#list each sample
MIX-270619_combined:

    # read information
    ## assume paired-end amplicon sequencing
    path: "~/barcodes/test_data"                    #absolute path to folder containing reads
    R1_pattern: "_R1.fastq.gz"                        #read files should be named <sample><R1_pattern> and <sample><R2_pattern>
    R2_pattern: "_R2.fastq.gz"
    adapter1: AGATCGGAAGAGCACACGTCTGAACTCCAGTCA     #adapters used for sequencing
    adapter2: AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT    
    fwdPrimer: gctggagttcgtgaccgccg                 #need to know this to know if merged reads are forward or reverse
    amplicon_length: 150                            #length of reads
    mismatches: 1                                   #optionally, state number of mismatches to allow
    extend: 1                                       #optionally, state number of bases to extend either side of expected position in search
    barcodes: "~/barcodes/MIX-270619_sample_barcodes.yml"        #path to file containing capsid barcodes

    
                                                     
