# https://blog.abbasmj.com/implementing-redis-task-queues-and-deploying-on-docker-compose

version: '3'
services:
    redis:
        image: redis:5.0.14-alpine
        ports:
          - "6379:6379"
        volumes:
            - ./redis:/redis

    flask-app:
        image: szsctt/barcodes:latest
#        container_name: flask-app
#        build: .
        restart: on-failure
        ports:
            - '5000:5000'
        volumes:
            - tmp:/tmp

    worker:
        image: szsctt/barcodes:latest
        depends_on:
            - redis
        command: rq worker --url redis://redis:6379
        links:
            - redis
        volumes:
            - tmp:/tmp
            
volumes:
     tmp: 
