sim_0:
    R1_pattern: ".R1.fq"  
    R2_pattern: ".R2.fq"                 
    adapter1: "ACACGTCTGAACTCCAGTCA"  
    adapter2: "GTCGTGTAGGGAAAGAGTGT" 
    min_length: 169    
    max_length: 181   
    fwdPrimer: "cactaagc"     
    debug_folder: "/usr/local/out/sim_0/"
    barcodes: "/usr/local/config/barcodes_0.yml"  
    path: "/usr/local/data/"   
sim_1:
    R1_pattern: ".R1.fq"              
    R2_pattern: ".R2.fq"                 
    adapter1: "ACACGTCTGAACTCCAGTCA" 
    adapter2: "GTCGTGTAGGGAAAGAGTGT"  
    min_length: 169                   
    max_length: 181                   
    fwdPrimer: "cactaagc"                               
    debug_folder: "/usr/local/out/sim_1/"
    barcodes: "/usr/local/config/barcodes_0.yml"   
    path: "/usr/local/data/"    
sim_2:
    R1_pattern: ".R1.fq"                
    R2_pattern: ".R2.fq"                 
    adapter1: "ACACGTCTGAACTCCAGTCA"    
    adapter2: "GTCGTGTAGGGAAAGAGTGT"   
    min_length: 206                                
    max_length: 206                              
    fwdPrimer: "caacttct"                                   
    debug_folder: "/usr/local/out/sim_2/"
    barcodes: "/usr/local/config/barcodes_1.yml"   
    path: "/usr/local/data/"      
sim_3:
    R1_pattern: ".R1.fq"                 
    R2_pattern: ".R2.fq"                 
    adapter1: "ACACGTCTGAACTCCAGTCA"    
    adapter2: "GTCGTGTAGGGAAAGAGTGT"   
    min_length: 206                             
    max_length: 206                          
    fwdPrimer: "caacttct"                                  
    debug_folder: "/usr/local/out/sim_3/"
    barcodes: "/usr/local/config/barcodes_1.yml" 
    path: "/usr/local/data/"      
