- test0: 
    type: constant
    start: 0 #expected start base of this barcode in the read
    barcodes:
        test0_0: AGGTAC 
        test0_1: GTCGTG
        test0_2: GTCTAA

- test1: 
    type: variable      # read contains an insertion of unknown length, but must contain the 'before' sequence before the insertion and the 'after' sequence after the insertion
    translate: true     # true or false
    before: "gctgac"
    after: "aggacc"
